FROM node:alpine
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
COPY ./ ./
RUN npm i --legacy-peer-deps
RUN npm install nodemon
RUN npm install -g prisma
RUN prisma generate
# RUN prisma db seed 
# RUN redis-server --daemonize yes
# EXPOSE 4000
CMD ["npm", "run", "dev"]